# Generated by Django 3.0.3 on 2020-07-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_customuser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='namey',
        ),
    ]
