# Generated by Django 3.0.3 on 2020-07-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_auto_20200714_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='namey',
            new_name='name',
        ),
    ]
