# Generated by Django 3.0.3 on 2020-07-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_auto_20200714_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/products/default.png', upload_to='images/products'),
        ),
    ]
